name: Update EPG

# Run daily at midnight UTC, and can also be triggered manually
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Install dependencies from package.json
      - name: Install dependencies
        run: npm install

      # 4️⃣ Run the EPG edit script
      - name: Run EPG Edit Script
        run: npm run edit

      # 5️⃣ Commit & push updated EPG
      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/epg6_modified.xml.gz
          git commit -m "Update EPG" || echo "No changes to commit"
          git push
