name: Update EPG

# Run daily at midnight UTC and allow manual trigger
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Run the EPG edit script
      - name: Run EPG Edit Script
        run: npm run edit

      # 5️⃣ Ensure public folder exists
      - name: Ensure public folder exists
        run: mkdir -p public

      # 6️⃣ Commit and push updated EPG (fixed shell syntax)
      - name: Commit and Push Updated EPG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [ -f public/epg6_modified.xml.gz ]; then
            git add public/epg6_modified.xml.gz
            git commit -m "Update EPG" || echo "No changes to commit"
            git push
          else
            echo "EPG file not found, nothing to commit"
          fi
